# Generated by ChatGPT - Add metadata fields to SousTheme
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_soustheme_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='soustheme',
            name='definition_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soustheme',
            name='unite_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soustheme',
            name='indication_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soustheme',
            name='source_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soustheme',
            name='periodicite_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soustheme',
            name='couverture_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
