# Generated by ChatGPT - Add archived flag to Theme
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_soustheme_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
