# Generated by Django 6.0.1 on 2026-02-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_theme_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='soustheme',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
