# Generated by Django 6.0.1 on 2026-02-02 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_categorie_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='is_visible',
        ),
    ]
