# Generated by Django 6.0.1 on 2026-02-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_categorie_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
