# Generated by Django 6.0.2 on 2026-02-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='soustheme',
            name='visitor_default_filters',
            field=models.JSONField(blank=True, default=dict, help_text='Filtres par défaut pour le visiteur'),
        ),
        migrations.AddField(
            model_name='soustheme',
            name='visitor_filters',
            field=models.JSONField(blank=True, default=list, help_text='Filtres disponibles pour le visiteur'),
        ),
        migrations.AddField(
            model_name='soustheme',
            name='visitor_visible_columns',
            field=models.JSONField(blank=True, default=list, help_text='Colonnes visibles pour le mode visiteur'),
        ),
    ]
