# Generated by Django 6.0.2 on 2026-02-22 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_soustheme_visitor_pivot_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soustheme',
            name='generated_flat_table',
        ),
        migrations.RemoveField(
            model_name='soustheme',
            name='generated_flat_table_source',
        ),
        migrations.RemoveField(
            model_name='soustheme',
            name='generated_flat_table_updated',
        ),
    ]
