# Generated by Django 6.0.2 on 2026-03-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_infobanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(default='À propos de la plateforme', max_length=255)),
                ('about_text', models.TextField(default='Cette plateforme centralise les statistiques régionales pour une consultation claire, fiable et actualisée.')),
                ('contact_title', models.CharField(default='Contact', max_length=255)),
                ('contact_email', models.EmailField(default='contact@hcp.ma', max_length=254)),
                ('contact_phone', models.CharField(default='+212 5 23 00 00 00', max_length=80)),
                ('contact_address', models.TextField(default='Direction Régionale HCP\nBéni Mellal - Khénifra')),
                ('contact_hours', models.CharField(default='Lundi - Vendredi, 08:30 - 16:30', max_length=255)),
                ('useful_links', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_contents_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
