"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import importlib
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(path):
    if not path.exists() or not path.is_file():
        return
    for raw_line in path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value


_load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def _env_bool(name, default=False):
    return str(os.getenv(name, str(default))).strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(name, default=''):
    raw = os.getenv(name, default)
    return [item.strip() for item in str(raw).split(',') if item.strip()]


def _env_float(name, default=0.0):
    raw = os.getenv(name, str(default))
    try:
        return float(str(raw).strip())
    except Exception:
        return float(default)


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'unsafe-dev-key-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost,testserver')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'core',
    'rest_framework',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'core.middleware.RequestContextMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.SecurityHeadersMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# PostgreSQL only: no sqlite fallback to avoid accidental empty local DB usage.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'hcp_db'),
        'USER': os.getenv('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
        'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

_default_cors_origins = 'http://localhost:5173,http://127.0.0.1:5173'
CORS_ALLOWED_ORIGINS = _env_list('DJANGO_CORS_ALLOWED_ORIGINS', _default_cors_origins)
# In local development Vite may pick another port when 5173 is busy.
# Allow localhost/127.0.0.1 on any port to avoid false CORS failures.
CORS_ALLOWED_ORIGIN_REGEXES = [r'^https?://localhost:\d+$', r'^https?://127\.0\.0\.1:\d+$'] if DEBUG else []
CSRF_TRUSTED_ORIGINS = _env_list('DJANGO_CSRF_TRUSTED_ORIGINS', 'http://localhost:5173,http://127.0.0.1:5173')
AUTH_USER_MODEL = 'core.CustomUser'

# Configuration REST Framework pour l'authentification
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.authentication.CookieOrHeaderTokenAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.getenv('DRF_THROTTLE_ANON', '120/min'),
        'user': os.getenv('DRF_THROTTLE_USER', '600/min'),
        'login': os.getenv('DRF_THROTTLE_LOGIN', '15/min'),
        'password_reset': os.getenv('DRF_THROTTLE_PASSWORD_RESET', '8/min'),
    },
}

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
REFERRER_POLICY = 'strict-origin-when-cross-origin'

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = os.getenv('DJANGO_SESSION_COOKIE_SAMESITE', 'Lax')
CSRF_COOKIE_SAMESITE = os.getenv('DJANGO_CSRF_COOKIE_SAMESITE', 'Lax')
CORS_ALLOW_CREDENTIALS = _env_bool('DJANGO_CORS_ALLOW_CREDENTIALS', True)

AUTH_TOKEN_COOKIE_NAME = os.getenv('DJANGO_AUTH_TOKEN_COOKIE_NAME', 'auth_token')
AUTH_TOKEN_COOKIE_AGE = int(os.getenv('DJANGO_AUTH_TOKEN_COOKIE_AGE', str(60 * 60 * 24 * 7)))
AUTH_TOKEN_COOKIE_SECURE = _env_bool('DJANGO_AUTH_TOKEN_COOKIE_SECURE', not DEBUG)
AUTH_TOKEN_COOKIE_SAMESITE = os.getenv('DJANGO_AUTH_TOKEN_COOKIE_SAMESITE', 'Lax')
AUTH_TOKEN_TTL_SECONDS = int(os.getenv('DJANGO_AUTH_TOKEN_TTL_SECONDS', str(60 * 60 * 24 * 7)))
AUTH_COOKIE_REQUIRE_CSRF = _env_bool('DJANGO_AUTH_COOKIE_REQUIRE_CSRF', True)

DEFAULT_CSP_HEADER = (
    "default-src 'self'; "
    "script-src 'self'; "
    "style-src 'self' 'unsafe-inline'; "
    "img-src 'self' data: blob: https:; "
    "font-src 'self' data:; "
    "connect-src 'self' http://127.0.0.1:8000 http://localhost:8000; "
    "object-src 'none'; "
    "base-uri 'self'; "
    "form-action 'self'; "
    "frame-ancestors 'none'"
)

CSP_ENABLED = _env_bool('DJANGO_CSP_ENABLED', True)
CSP_REPORT_ONLY = _env_bool('DJANGO_CSP_REPORT_ONLY', True)
CSP_HEADER_VALUE = os.getenv('DJANGO_CSP_HEADER', DEFAULT_CSP_HEADER)
PERMISSIONS_POLICY = os.getenv('DJANGO_PERMISSIONS_POLICY', 'geolocation=(), microphone=(), camera=()')


def _ensure_production_security():
    if DEBUG:
        return

    if SECRET_KEY == 'unsafe-dev-key-change-me':
        raise ImproperlyConfigured('DJANGO_SECRET_KEY doit etre configure en production.')

    if not DATABASES['default'].get('PASSWORD'):
        raise ImproperlyConfigured('POSTGRES_PASSWORD doit etre configure en production.')

    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured('DJANGO_ALLOWED_HOSTS doit contenir au moins un host en production.')


_ensure_production_security()

# Configuration Email
EMAIL_BACKEND = os.getenv('DJANGO_EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('DJANGO_EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('DJANGO_EMAIL_PORT', '587'))
EMAIL_USE_TLS = _env_bool('DJANGO_EMAIL_USE_TLS', True)
EMAIL_HOST_USER = os.getenv('DJANGO_EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('DJANGO_EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DJANGO_DEFAULT_FROM_EMAIL', 'noreply@hcp.ma')

if not DEBUG:
    SECURE_SSL_REDIRECT = _env_bool('DJANGO_SECURE_SSL_REDIRECT', True)
    SESSION_COOKIE_SECURE = _env_bool('DJANGO_SESSION_COOKIE_SECURE', True)
    CSRF_COOKIE_SECURE = _env_bool('DJANGO_CSRF_COOKIE_SECURE', True)
    SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', True)
    SECURE_HSTS_PRELOAD = _env_bool('DJANGO_SECURE_HSTS_PRELOAD', True)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s %(levelname)s request_id=%(request_id)s %(name)s %(message)s'
        }
    },
    'filters': {
        'request_id': {
            '()': 'core.middleware.RequestIdLogFilter',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
            'filters': ['request_id'],
        },
    },
    'loggers': {
        'security': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_SECURITY_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': True,
        },
        'core': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}


SENTRY_DSN = os.getenv('SENTRY_DSN', '').strip()
SENTRY_ENABLED = _env_bool('SENTRY_ENABLED', False)
if SENTRY_ENABLED and SENTRY_DSN:
    try:
        sentry_sdk = importlib.import_module('sentry_sdk')
        sentry_django = importlib.import_module('sentry_sdk.integrations.django')
        django_integration = sentry_django.DjangoIntegration

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[django_integration()],
            traces_sample_rate=_env_float('SENTRY_TRACES_SAMPLE_RATE', 0.0),
            profiles_sample_rate=_env_float('SENTRY_PROFILES_SAMPLE_RATE', 0.0),
            send_default_pii=_env_bool('SENTRY_SEND_DEFAULT_PII', False),
            environment=os.getenv('DJANGO_ENV', 'development'),
        )
    except Exception as sentry_exc:
        import logging
        logging.getLogger('core').warning('Sentry non initialise: %s', sentry_exc)


