# Generated by Django 6.0.1 on 2026-01-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soustheme',
            name='data_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
