# Generated by Django 6.0.1 on 2026-01-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_soustheme_data_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='soustheme',
            name='charts_config',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
