# Generated by Django 6.0.1 on 2026-01-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_soustheme_charts_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='definition_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='indication_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='periodicite_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='source_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='statut',
            field=models.CharField(default='Public', max_length=50),
        ),
        migrations.AddField(
            model_name='theme',
            name='unite_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
