# Generated by ChatGPT - Add is_visible to SousTheme
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_theme_definition_text_theme_indication_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soustheme',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
