# Generated by Django 6.0.1 on 2026-02-02 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_soustheme_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('ordre', models.IntegerField(default=0)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.theme')),
            ],
        ),
        migrations.AddField(
            model_name='soustheme',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_themes', to='core.categorie'),
        ),
    ]
