# Generated by Django 6.0.1 on 2026-02-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_categorie_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='soustheme',
            name='est_sommable',
            field=models.BooleanField(default=True, help_text='Si Vrai, on peut additionner les données. Si Faux, on calcule des moyennes.'),
        ),
        migrations.AddField(
            model_name='soustheme',
            name='filtres_disponibles',
            field=models.JSONField(blank=True, default=list, help_text='Liste des colonnes sur lesquelles on peut filtrer'),
        ),
        migrations.AddField(
            model_name='soustheme',
            name='niveau_geo',
            field=models.CharField(blank=True, choices=[('Régionale', 'Régionale'), ('Provinciale', 'Provinciale'), ('Communale', 'Communale')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='soustheme',
            name='type_unite',
            field=models.CharField(blank=True, help_text="Ex: '%', 'Effectif', 'DH', 'Km'", max_length=100, null=True),
        ),
    ]
