# Generated by Django 6.0.1 on 2026-02-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userrequest_userthemeassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userthemeassignment',
            name='date_completion',
            field=models.DateTimeField(blank=True, help_text='Date de complétion de la tâche', null=True),
        ),
        migrations.AddField(
            model_name='userthemeassignment',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes ou commentaires sur la tâche', null=True),
        ),
        migrations.AddField(
            model_name='userthemeassignment',
            name='priorite',
            field=models.CharField(choices=[('Basse', 'Basse'), ('Normale', 'Normale'), ('Haute', 'Haute')], default='Normale', max_length=20),
        ),
        migrations.AddField(
            model_name='userthemeassignment',
            name='progression',
            field=models.IntegerField(default=0, help_text='Pourcentage de progression (0-100)'),
        ),
    ]
