# Generated by Django 6.0.1 on 2026-02-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userthemeassignment_date_completion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soustheme',
            name='columns_order',
            field=models.JSONField(blank=True, default=list, help_text='Liste ordonnée des noms de colonnes du fichier Excel'),
        ),
    ]
