# Generated by Django 6.0.2 on 2026-02-13 22:33

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_soustheme_columns_order'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', core.models.CustomUserManager()),
            ],
        ),
    ]
