# Generated by Django 6.0.2 on 2026-02-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_soustheme_visitor_default_filters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soustheme',
            name='generated_flat_table',
            field=models.JSONField(blank=True, help_text="Tableau plat généré par l'IA (liste d'objets)", null=True),
        ),
        migrations.AddField(
            model_name='soustheme',
            name='generated_flat_table_source',
            field=models.CharField(blank=True, help_text='Source du flattening (gemini|hf|fallback)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soustheme',
            name='generated_flat_table_updated',
            field=models.DateTimeField(blank=True, help_text='Dernière mise à jour du tableau généré', null=True),
        ),
    ]
